version: '3.8'
services:
  etcd-node1:
    image: bitnami/etcd:latest
    container_name: etcd-node1
    depends_on:
      etcd-node2:
        condition: service_started
      etcd-node3:
        condition: service_started
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment-net
    volumes:
      - /Users/vinoctis/Work/docker-data/etcd/node1:/etcd-data
    ports:
      - 2379:2379
      - 2380:2380
    healthcheck:
      test: ["CMD-SHELL", "ETCDCTL_API=3 etcdctl --endpoints=http://localhost:2379 endpoint health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
  etcd-node2:
    image: bitnami/etcd:latest
    container_name: etcd-node2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node2
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment-net
    volumes:
      - /Users/vinoctis/Work/docker-data/etcd/node2:/etcd-data
  etcd-node3:
    image: bitnami/etcd:latest
    container_name: etcd-node3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment-net
    volumes:
       - /Users/vinoctis/Work/docker-data/etcd/node3:/etcd-data
  mysql:
    env_file:
      - ./payment/.env
    image: arm64v8/mysql:8.0 
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${PAYMENT_PASSWORD}
      MYSQL_DATABASE: ${PAYMENT_DATABASE}
    ports:
      - 33060:3306
    volumes:
      - /Users/vinoctis/Work/docker-data/mysql/:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h127.0.0.1 -uroot -p${PAYMENT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 500M
    networks:
      - payment-net
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment-service
    image: local/payment-alpine:v1.0.2
    depends_on:
      mysql:
        condition: service_healthy
      etcd-node1: 
        condition: service_healthy
    networks:
      - payment-net
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - /Users/vinoctis/Work/docker-data/payment/logs:/logs
networks:
  payment-net:
    external: true