version: '3.8'
services:
  etcd-node1:
    image: bitnami/etcd:latest
    container_name: etcd-node1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment-net
    volumes:
      - /Users/vinoctis/Work/docker-data/etcd/node1:/etcd-data
    ports:
      - 2379:2379
      - 2380:2380
    test: ["CMD", "etcdctl", "--endpoints=http://localhost:2379",  "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
  etcd-node2:
    image: bitnami/etcd:latest
    container_name: etcd-node2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node2
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment-net
    volumes:
      - /Users/vinoctis/Work/docker-data/etcd/node2:/etcd-data
  etcd-node3:
    image: bitnami/etcd:latest
    container_name: etcd-node3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
    networks:
      - payment
    volumes:
       - /Users/vinoctis/Work/docker-data/etcd/node3:/etcd-data
  mysql:
    image: arm64v8/mysql:8.0 
    container_name: mysql8
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 33060:3306
    volumes:
      - /Users/vinoctis/Work/docker-data/mysql/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - payment-net
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    depends_on:
      mysql8:
        condition: service_healthy
      etcd-node1: 
        condition: service_healthy
    networks:
      - payment-net
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - /Users/vinoctis/Work/docker-data/payment/logs:/logs
networks:
  payment-net:
    external: true